
GET http://localhost:8080/api/events

###

GET http://localhost:8080/api/events?offset=2&count=4

###

GET http://localhost:8080/api/events/5b1fd490de2774088cfed79c

###


POST http://localhost:8080/api/events
Content-Type: application/json

{
    "name":"Фестивалю 'Добрі справи 2018' потрібен логотип V",
    "description":"'Добрі справи 2018'- фестиваль, що має за мету зібрати в одному місці велику кулькість людей які займаються благодійністтю та роблять добрі справи. Зокрема це будуть громадські організації та благодійні фонди, а також ініціативні групи чи люди які своїми соціальними проектами чи добрими вчинками зробили великий внесок в скарбницю добрих справ і заслуговують розказати про себе і залучити до своєї діяльності як можна більше людей з числа гостей фестивалю. А ще на всіх гостей фестивалю чекатиме сюрприз в формі інтерактивнлї гри, в якій зможе взяти участь кожен і виграти подарунки від наших спонсорів та партнерів.",
    "organization":"Добрі справи 2018",
    "contacts":"+38098678594",
    "interests":"2018-05-03T08:06:52.005Z",
    "location":"Чернігів, Україна",
    "photo":"photo-event_vwr3vn",
    "category":"Nonprofit"}

###

DELETE http://localhost:8080/api/events/5b1fd4b3de2774088cfed7bb

###

PATCH http://localhost:8080/api/events/5b1fd4a4de2774088cfed7b0
Content-Type: application/json

{
    "name": "Find job"
}

###







