
GET http://localhost:8080/api/users

###

GET http://localhost:8080/api/users?offset=2

###

GET http://localhost:8080/api/users/5b1fd178de2774088cfed5c7

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "name": "Victor Frankl 1",
    "description": "He works in Non profit organizaion LEF full time, which spread eco-initiatives. Robert believes that by using conservation as a tool will not only protect our remarkable natural world, but also will protect and improve human lives. He wants to attract more people to their initiative.",
    "contacts": "+38098678594",
    "location": "Odesa, Ukraine",
    "photo": "njhniezzny9ja9xmlfun",
    "interests": "Murders"
}

###

DELETE http://localhost:8080/api/users/5b1fda3c1e7a02365a555224

###


PATCH http://localhost:8080/api/users/edit/5b1fd33bde2774088cfed6ab
Content-Type: application/json

{
    "name": "Olgam"
}

###





